config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in" => "public/sessions#guest_sign_in"
  end

  devise_for :admin,  skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    get "search_tag" => "posts#search_tag"
    get "privacy" => "homes#privacy", as: "privacy"
    get "users/my_page/:id" => "users#show", as: "users_my_page"
    get "users/information/edit" => "users#edit", as: "users_information_edit"
    patch "users/information" => "users#update"
    get "users/unsubscribe"
    patch "users/withdraw"
    resources :users, only: [] do
      resources :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    post "/post/:post_id/items/:id/toggle" => "items#toggle"
    resources :posts, only: [:index, :create, :show, :update, :destroy] do
      delete "itineraries/destroy_all" => "itineraries#destroy_all"
      resources :itineraries, only: [:show, :create, :update, :destroy] do
        resources :articles, only: [:create, :destroy]
        resources :prices, only: [:create, :destroy]
      end
      resources :post_comments, only: [:index, :create, :update, :destroy]
      resource :favorites, only: [:create, :destroy] # urlにID含めない
      resources :items, only: [:index, :create, :destroy]
    end
    # グループ一覧の表示
    get "groups/:id/permits" => "groups#permits", as: "permits"
    delete "groups/:group_id/permits/:id/cancel_request" => "permits#cancel_request", as: "cancel_request"
    resources :groups, only: [:index, :show, :create, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
      resource :rooms, only: [:show, :create] do
        resources :messages, only: [:create]
      end
    end
    resources :notifications, only: [:update]

    post "contacts/confirm" => "contacts#confirm", as: "confirm"
    get "contacts/confirm", to: "contacts#error", as: "error"
    post "contacts/back" => "contacts#back", as: "back"
    get "done" => "contacts#done", as: "done"
    resources :contacts, only: [:create]
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :users, only: [:index, :edit, :show, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:index, :destroy]
    end
    resources :groups, only: [:index, :show, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :itineraries, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy # 投稿画面で表示したいから中間テーブル経由でのこの記載をする
  has_many :items, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :title, presence: true
  validates :start_date, presence: true
  validates :finish_date, presence: true
  validate :finish_date_after_start_date



  def self.looks(word)
    if word == ""
      Post.all
    else
      Post.where("title LIKE ?", "%#{word}%")
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tags(tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name: new_name)
      self.tags << tag
    end
  end


  def update_tags(latest_tags)
    if self.tags.empty? # 既存のタグがない場合、追加のみ行う 初回ではタグ登録をしていなく、２回目でタグ登録をした
      latest_tags.each do |latest_tag|
        self.tags.find_or_create_by(name: latest_tag)
      end
    elsif latest_tags.empty? # 更新対象のタグがなかったら既存のタグを全て削除　元々タグを登録していて、からで更新した時
      self.tags.each do |tag|
        self.tags.delete(tag)
      end
    else # 既存のタグも更新対象のタグもある場合、差分更新
      current_tags = self.tags.pluck(:name)
      old_tags = current_tags - latest_tags # 左側を基準に考える b-abc = ""
      new_tags = latest_tags - current_tags # abc-b=ac

      new_tags.each do |new_tag|
        self.tags.find_or_create_by(name: new_tag)
      end

      old_tags.each do |old_tag|
        tag = self.tags.find_by(name: old_tag)
        self.tags.delete(tag) if tag.present?
      end

    end
  end

  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id, notifiable_type: "Post", notifiable_id: id)
    end
  end

  enum status: { published: 0, draft: 1, unpublished: 2 }

  # 終了日が開始日より後に来ないようにバリデーション
  def finish_date_after_start_date
    return if start_date.nil? || finish_date.nil?
    errors.add(:finish_date, "は開始日より後の日付にしてください") if start_date >= finish_date
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @itineraries = @post.itineraries.order(start_time: :asc).page(params[:page])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: "該当の投稿を削除しました"
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<table class="table table-hover mt-3">
  <thead class="text-center">
    <tr>
      <th class="bar-th">投稿日</th>
      <th class="bar-th">投稿者</th>
      <th class="bar-th">開始日</th>
      <th class="bar-th">終了日</th>
      <th class="bar-th">タイトル</th>
    </tr>
  </thead>
  <tbody  class="text-center">
    <% posts.each do |post| %>
    <tr  onclick='window.location="<%= admin_post_path(post) %>"' role="link">
      <td><%= post.created_at.to_s(:datetime_jp) %></td>
      <td class="align-middle">
        <div class="row">
          <%= link_to admin_user_path(post.user) ,class: "text-dark" do %>
            <div class="text-center">
              <%= image_tag post.user.get_profile_image, size: '64x36', style: "object-fit: contain;" %>
            </div>
            <div class="text-center">
              <%= post.user.name %>
            </div>
          <% end %>  
        </div>
      </td>
      <td><%= post.start_date.strftime("%Y/%m/%d") %></td>
      <td><%= post.finish_date.strftime("%Y/%m/%d") %></td>
      <td>
        <%= post.title %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/_index_bar.html.erb
<div class="row  bg-gray ">
  <table class="table text-center">
    <tr>
      <td colspan="2"><%= image_tag post.user.get_profile_image %></td>
    </tr>
    <tr>
      <th class="bar-th">投稿者</th>
      <td>
        <%= link_to admin_user_path(post.user) do %>
          <%= post.user.name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th class="bar-th">開始日</th>
      <td><%= post.start_date.strftime("%Y/%m/%d") %></td>
    </tr>
    <tr>
      <th class="bar-th">終了日</th>
      <td><%= post.finish_date.strftime("%Y/%m/%d") %></td>
    </tr>
    <tr>
      <th class="bar-th">タイトル</th>
      <td><%= post.title %></td>
    </tr>
    <tr>
      <th>詳細</th>
      <td><%= post.body %></td>
    </tr>
    <tr>
      <th class="bar-th">コメント数</th>
      <td>
        <p><%= post.post_comments.count %> コメント</p>
        <p><%= link_to "コメントはこちら", admin_post_post_comments_path(post) %></p>
      </td>
    </tr>
  </table>
  
  <div class="container">
    <div class="row m-3">
      <%= link_to '削除する', admin_post_path(post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-block btn-secondary" %>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="m-3 text-center">投稿一覧</h2>
    <div class="heading-line-admin"></div>
  </div>
  <div class="row">
    <div class="col">
      <%= render 'admin/posts/index', posts: @posts %>
    </div>
    <%= paginate @posts , theme: 'bootstrap-5'%>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= render 'index_bar', post: @post %>
    </div>
    <div class="col-md-7 offset-md-1">
        <div class="row text-center m-3">
          <h2>投稿詳細</h2>
          <div class="heading-line-admin "></div>
        </div>
      <div class="row mt-3">
        <% if @itineraries.present? %>
          <%= render 'public/itineraries/index', post: @post, itineraries: @itineraries %>
        <% else %>
          <div class="bg-orange">
            <p class="fw-bold text-center m-5">旅程はありません</p>
          </div>
        <% end %>  
      </div>
    </div>
  </div>
</div>