config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in" => "public/sessions#guest_sign_in"
  end

  devise_for :admin,  skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    get "search_tag" => "posts#search_tag"
    get "privacy" => "homes#privacy", as: "privacy"
    get "users/my_page/:id" => "users#show", as: "users_my_page"
    get "users/information/edit" => "users#edit", as: "users_information_edit"
    patch "users/information" => "users#update"
    get "users/unsubscribe"
    patch "users/withdraw"
    resources :users, only: [] do
      resources :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    post "/post/:post_id/items/:id/toggle" => "items#toggle"
    resources :posts, only: [:index, :create, :show, :update, :destroy] do
      delete "itineraries/destroy_all" => "itineraries#destroy_all"
      resources :itineraries, only: [:show, :create, :update, :destroy] do
        resources :articles, only: [:create, :destroy]
        resources :prices, only: [:create, :destroy]
      end
      resources :post_comments, only: [:index, :create, :update, :destroy]
      resource :favorites, only: [:create, :destroy] # urlにID含めない
      resources :items, only: [:index, :create, :destroy]
    end
    # グループ一覧の表示
    get "groups/:id/permits" => "groups#permits", as: "permits"
    delete "groups/:group_id/permits/:id/cancel_request" => "permits#cancel_request", as: "cancel_request"
    resources :groups, only: [:index, :show, :create, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
      resource :rooms, only: [:show, :create] do
        resources :messages, only: [:create]
      end
    end
    resources :notifications, only: [:update]

    post "contacts/confirm" => "contacts#confirm", as: "confirm"
    get "contacts/confirm", to: "contacts#error", as: "error"
    post "contacts/back" => "contacts#back", as: "back"
    get "done" => "contacts#done", as: "done"
    resources :contacts, only: [:create]
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :users, only: [:index, :edit, :show, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:index, :destroy]
    end
    resources :groups, only: [:index, :show, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :comment, presence: true, length: { maximum: 150 }

  def self.looks(word)
    if word == ""
      PostComment.all
    else
      PostComment.where("comment LIKE ?", "%#{word}%")
    end
  end

  after_create do
    notifications.create(user_id: post.user.id, post_id: post.id, notifiable_type: "PostComment", notifiable_id: id)
  end
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @post = Post.find(params[:post_id])
    @post_comments = @post.post_comments.page(params[:page])
  end

  def destroy
    @post_comment = PostComment.find(params[:id])
    @post_comment.destroy
    redirect_to admin_post_post_comments_path, notice: "コメントの削除に成功しました"
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/_index.html.erb
<% if post_comments.present? %>
  <table class="table mt-3">
    <tr>
      <th>投稿日時</th>
      <th>コメント投稿者</th>
      <th>コメント</th>
      <th></th>
    </tr>
    <% post_comments.each do |post_comment| %>
    <tr>
      <td><%= post_comment.created_at.to_s(:datetime_jp) %></td>
      <td>
        <%= link_to admin_user_path(post_comment.user) do %>
          <%= post_comment.user.name %>
        <% end %>
      </td>
      <td><%= post_comment.comment %></td>
      <td><%= link_to "削除",admin_post_post_comment_path(post_comment.post, post_comment), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-secondary"%></td>
    </tr>
    <% end %>
  </table>
  <%= paginate post_comments , theme: 'bootstrap-5'%>
<% else %>
  <div class="bg-orange">
    <p class="fw-bold text-center m-5">コメントはありません</p>
  </div>
<% end %>  

app/views/admin/post_comments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <%= render 'admin/posts/index_bar', post: @post %>
    </div>
    <div class="col-7 offset-1">
      <h3 class="m-3 text-center">コメント一覧</h3>
      <div class="heading-line-admin "></div>
      <%= render 'admin/post_comments/index', post_comments: @post_comments %>
    </div>
  </div>
</div>