config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in" => "public/sessions#guest_sign_in"
  end

  devise_for :admin,  skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    get "search_tag" => "posts#search_tag"
    get "privacy" => "homes#privacy", as: "privacy"
    get "users/my_page/:id" => "users#show", as: "users_my_page"
    get "users/information/edit" => "users#edit", as: "users_information_edit"
    patch "users/information" => "users#update"
    get "users/unsubscribe"
    patch "users/withdraw"
    resources :users, only: [] do
      resources :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    post "/post/:post_id/items/:id/toggle" => "items#toggle"
    resources :posts, only: [:index, :create, :show, :update, :destroy] do
      delete "itineraries/destroy_all" => "itineraries#destroy_all"
      resources :itineraries, only: [:show, :create, :update, :destroy] do
        resources :articles, only: [:create, :destroy]
        resources :prices, only: [:create, :destroy]
      end
      resources :post_comments, only: [:index, :create, :update, :destroy]
      resource :favorites, only: [:create, :destroy] # urlにID含めない
      resources :items, only: [:index, :create, :destroy]
    end
    # グループ一覧の表示
    get "groups/:id/permits" => "groups#permits", as: "permits"
    delete "groups/:group_id/permits/:id/cancel_request" => "permits#cancel_request", as: "cancel_request"
    resources :groups, only: [:index, :show, :create, :update, :destroy] do
      resource :group_users, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
      resource :rooms, only: [:show, :create] do
        resources :messages, only: [:create]
      end
    end
    resources :notifications, only: [:update]

    post "contacts/confirm" => "contacts#confirm", as: "confirm"
    get "contacts/confirm", to: "contacts#error", as: "error"
    post "contacts/back" => "contacts#back", as: "back"
    get "done" => "contacts#done", as: "done"
    resources :contacts, only: [:create]
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :users, only: [:index, :edit, :show, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:index, :destroy]
    end
    resources :groups, only: [:index, :show, :edit, :update, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger text-center">
    <h4><%= obj.errors.count %> 件のエラーが発生しました</h4>
    <ul class="list-unstyled">
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success text-center mx-auto mt-2" style="width: 70%;"><%= flash[:notice] %></div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger text-center mx-auto mt-2" style="width: 70%;"><%= flash[:alert] %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="text-white mt-2">
  <div class="container p-3">
  	<div class="justify-content-center" style="font-size :15px;">
  	  <div class="row d-flex justify-content-center text-center">
    	  <div class="col-12 col-lg-5">
    	    <div class="row">
    	      <h6 class="footer-h6 text-decoration-underline">About Us</h6>
    	    </div>
    	    <div class="row">
    	      <div>
    	        <%= link_to root_path do %>
                <%= image_tag "logo.png", :size => '230x80' %>
              <% end %>
    	      </div>
    	      <div>
    	        <p>
    	          旅行計画を無料で共有できる「シェアトリ」<br>
    	          旅行などのイベントを作成・共有することができます。
    	        </p>
    	      </div>
    	    </div>

    	  </div>
    	  <div class="col-12 col-lg-4">
    	    <div class="row">
    	      <h6 class="footer-h6 text-decoration-underline mb-3">お問い合わせ</h6>
    	    </div>
    	    <div class="row">
    	      <p class="m-0 p-0">運営元：株式会社sharetrip</p>
    	      <p class="m-0 p-0">〒〇〇〇-〇〇〇〇</p>
    	      <p class="m-0 p-0">東京都××××××××××××</p>
    	      <p class="m-0 p-0">MAIL:sample@example.com</p>
    	      <p class="m-0 p-0">TEL:123456789</p>
    	     </div>
    	  </div>
    	  <div class="col-12 col-lg-3">
    	    <div class="row">
    	      <h6 class="footer-h6 text-decoration-underline mb-3">その他</h6>
    	    </div>
    	    <div class="row">
    	      <p>
      	      <i class="fa-brands fa-instagram" style="font-size: 30px;"></i>　Instagram
      	    </p>
    	    </div>
    	    <div class="row">
    	      <%= link_to privacy_path, class: "text-decoration-none" do  %>
      	      <p class="text-white ">プライバシーポリシー</p>
      	    <% end %>
    	    </div>
    	  </div>
  	  </div>
    	<div class="row-12 mt-3 mx-auto text-white text-center">
    		<p>Copyright © Sharetrip All Rights Reserved.</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header sticky-top">
  <nav class="navbar navbar-expand-xl navbar-dark">
    <div class="container-fluid justify-content-center">
      <a class="navbar-brand col-12 col-md-4 col-xl-3 mr-0 mt-2 text-center" href="/"><%= image_tag "logo.png", :size => '200x60' %></a>
      <% unless admin_signed_in? %>
        <div class="col-12 col-md-4 col-xl-3 mt-4 d-flex align-items-center justify-content-center">
          <% if user_signed_in? %>
            <p class="py-2 px-3 border text-white">ようこそ、<strong><%= current_user.name %></strong>さん！</p>
          <% end %>
        </div>
      <% end %>
      <button class="col-12 col-md-4 navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="col mt-4">
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            <% if admin_signed_in? %>
              <li>
                <%= link_to 'ユーザー一覧', admin_users_path, class: " header-btn mb-2" %>
              </li>
              <li>
                <%= link_to '投稿一覧', admin_posts_path, class: "header-btn mb-2" %>
              </li>
              <li>
                <%= link_to 'グループ一覧', admin_groups_path, class: "header-btn mb-2" %>
              </li>
              <li>
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "header-btn mb-2" %>
              </li>
            <% elsif user_signed_in? %>
              <li>
                <%= link_to 'マイページ', users_my_page_path(current_user) , class: "header-btn" %>
              </li>
              <li>
                <%= link_to '投稿一覧', posts_path, class: "header-btn" %>
              </li>
              <li>
                <%= link_to 'グループ一覧', groups_path, class: " header-btn" %>
              </li>
              <li class="dropdown">
                <a class="header-btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  通知
                  <span class="badge badge-danger"><%= current_user.notifications.where(read: false).count %></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <% if current_user.notifications.where(read: false).any? %>
                    <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                    <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                      <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                    <% end %>
                  <% else %>
                    <span class="dropdown-item disabled">未読の通知はありません</span>
                  <% end %>
                </div>
              </li>
              <li>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: " header-btn" %>
              </li>
            <% else %>
              <li>
                <%= link_to '投稿一覧', posts_path, class: " header-btn" %>
              </li>
              <li>
                <%= link_to '新規登録', new_user_registration_path, class: " header-btn" %>
              </li>
              <li>
                <%= link_to 'ログイン', new_user_session_path, class: " header-btn" %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="text-right m-2">
          <% if user_signed_in? %>
            <%= render 'public/searches/search' %>
          <% elsif admin_signed_in? %>
            <%= render 'admin/searches/search' %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharetrip</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <script src="https://kit.fontawesome.com/6326117fc6.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.4/css/lightbox.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <main><%= yield %></main>
    <%= render 'layouts/footer' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.4/js/lightbox.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>